# Generated by Django 5.1.5 on 2025-02-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0005_place_requires_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mypp.place'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'place')},
        ),
    ]
