# Generated by Django 5.1.5 on 2025-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0006_alter_rating_place_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_per_adult',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='place',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
