# Generated by Django 5.1.5 on 2025-02-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0004_bookmark_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='requires_booking',
            field=models.BooleanField(default=False),
        ),
    ]
